require 'json'
require 'open3'

def node_resolve(package)
  stdout, stderr, status = Open3.capture3("node --print \"require.resolve('#{package}/package.json')\"")
  if status.success?
    return File.dirname(stdout.strip)
  else
    raise "Failed to resolve #{package}: #{stderr}"
  end
end

# Autolinking scripts for Expo & React Native
begin
  require File.join(node_resolve('expo'), 'scripts/autolinking')
rescue
  require_relative '../node_modules/expo/scripts/autolinking'
end

begin
  require File.join(node_resolve('react-native'), 'scripts/react_native_pods')
rescue
  require_relative '../node_modules/react-native/scripts/react_native_pods'
end

podfile_properties = JSON.parse(
  File.read(File.join(__dir__, 'Podfile.properties.json'))
) rescue {}

def ccache_enabled?(podfile_properties)
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

# Environment variables / flags
ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
  ENV['RCT_USE_RN_DEP'] ||= '1'
  ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1'
end

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'SmartSubscriptionTracker' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"]
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  # Use frameworks if configured
  if podfile_properties['ios.useFrameworks']
    use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym
  end
  if ENV['USE_FRAMEWORKS']
    use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym
  end

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => (
      podfile_properties['expo.jsEngine'].nil? ||
      podfile_properties['expo.jsEngine'] == 'hermes'
    ),
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => (
      podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false'
    ),
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # Exclude arm64 architecture for simulator to avoid issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config_build|
        config_build.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end